buildscript.run = false

['cfg(target_os = "windows")']
buildscript.run = true
extra_deps = [
    "//platforms/windows:advapi32.lib",
    "//platforms/windows:avrt.lib",
    "//platforms/windows:bcrypt.lib",
    "//platforms/windows:bluetoothapis.lib",
    "//platforms/windows:bthprops.lib",
    "//platforms/windows:cfgmgr32.lib",
    "//platforms/windows:comctl32.lib",
    "//platforms/windows:comdlg32.lib",
    "//platforms/windows:credui.lib",
    "//platforms/windows:crypt32.lib",
    "//platforms/windows:cryptnet.lib",
    "//platforms/windows:d2d1.lib",
    "//platforms/windows:d3d11.lib",
    "//platforms/windows:d3d12.lib",
    "//platforms/windows:d3d9.lib",
    "//platforms/windows:d3dcompiler.lib",
    "//platforms/windows:dbghelp.lib",
    "//platforms/windows:dcomp.lib",
    "//platforms/windows:dsound.lib",
    "//platforms/windows:dwmapi.lib",
    "//platforms/windows:dwrite.lib",
    "//platforms/windows:dxgi.lib",
    "//platforms/windows:dxva2.lib",
    "//platforms/windows:fwpuclnt.lib",
    "//platforms/windows:gdi32.lib",
    "//platforms/windows:hid.lib",
    "//platforms/windows:httpapi.lib",
    "//platforms/windows:imm32.lib",
    "//platforms/windows:iphlpapi.lib",
    "//platforms/windows:kernel32.lib",
    "//platforms/windows:ktmw32.lib",
    "//platforms/windows:mmdevapi.lib",
    "//platforms/windows:mpr.lib",
    "//platforms/windows:msimg32.lib",
    "//platforms/windows:mswsock.lib",
    "//platforms/windows:ncrypt.lib",
    "//platforms/windows:netapi32.lib",
    "//platforms/windows:ntdll.lib",
    "//platforms/windows:odbc32.lib",
    "//platforms/windows:ole32.lib",
    "//platforms/windows:oleaut32.lib",
    "//platforms/windows:opengl32.lib",
    "//platforms/windows:pdh.lib",
    "//platforms/windows:powrprof.lib",
    "//platforms/windows:psapi.lib",
    "//platforms/windows:rstrtmgr.lib",
    "//platforms/windows:runtimeobject.lib",
    "//platforms/windows:secur32.lib",
    "//platforms/windows:setupapi.lib",
    "//platforms/windows:shcore.lib",
    "//platforms/windows:shell32.lib",
    "//platforms/windows:shlwapi.lib",
    "//platforms/windows:sporder.lib",
    "//platforms/windows:synchronization.lib",
    "//platforms/windows:user32.lib",
    "//platforms/windows:userenv.lib",
    "//platforms/windows:usp10.lib",
    "//platforms/windows:uxtheme.lib",
    "//platforms/windows:version.lib",
    "//platforms/windows:vssapi.lib",
    "//platforms/windows:wer.lib",
    "//platforms/windows:wevtapi.lib",
    "//platforms/windows:windowscodecs.lib",
    "//platforms/windows:winhttp.lib",
    "//platforms/windows:wininet.lib",
    "//platforms/windows:winmm.lib",
    "//platforms/windows:winscard.lib",
    "//platforms/windows:winspool.lib",
    "//platforms/windows:wintrust.lib",
    "//platforms/windows:winusb.lib",
    "//platforms/windows:wlanapi.lib",
    "//platforms/windows:ws2_32.lib",
    "//platforms/windows:wtsapi32.lib",
    "//platforms/windows:xinput.lib",
]
