load("//constraints:defs.bzl", "configuration_transition")
load(
    ":defs.bzl",
    "ci_artifact",
    "ci_llvm",
    "stage0_download",
    "stage0_executable",
    "stage0_extract",
    "stage0_sysroot",
)

configuration_transition(
    name = "stage0_configuration",
    add_fallback_settings = "//platforms:host",
    keep_settings = [
        "prelude//cpu/constraints:cpu",
        "prelude//os/constraints:os",
    ],
)

stage0_download(
    name = "dist",
    components = [
        "cargo",
        "clippy",
        "rust-std",
        "rustc",
    ],
    incoming_transition = ":stage0_configuration",
    manifest = "//:stage0_manifest",
)

stage0_extract(
    name = "extract",
    dist = ":dist",
    incoming_transition = ":stage0_configuration",
)

stage0_executable(
    name = "rustc",
    dist = ":extract[rustc]",
    env = {"RUSTC_BOOTSTRAP": "1"},
    incoming_transition = ":stage0_configuration",
    visibility = ["PUBLIC"],
)

stage0_executable(
    name = "rustdoc",
    dist = ":extract[rustc]",
    env = {"RUSTC_BOOTSTRAP": "1"},
    incoming_transition = ":stage0_configuration",
    visibility = ["PUBLIC"],
)

stage0_executable(
    name = "clippy-driver",
    dist = ":extract[clippy]",
    incoming_transition = ":stage0_configuration",
    libdir = ":extract[rustc]",
    visibility = ["PUBLIC"],
)

stage0_sysroot(
    name = "sysroot",
    dist = ":dist[rust-std]",
    incoming_transition = ":stage0_configuration",
    visibility = ["PUBLIC"],
)

ci_artifact(
    name = "rust_dev",
    commit = "1afd73112f4ad9cad106573a830d2f9c4ffb89e9",
    component = "rust-dev-beta",
    incoming_transition = ":stage0_configuration",
    manifest = "//:stage0_manifest",
    sha256 = {
        "aarch64-apple-darwin": "c74dce363f675b0ed5b13af42db0c00b69f4b372ce5388ea3b74c1e58c681e16",
        "aarch64-pc-windows-msvc": "d43b3c85d993c2e702cae7a52b490723467647bc2c4d8ef9f2e996d7740109cb",
        "aarch64-unknown-linux-gnu": "436b51e663ac9835acf8b0d8bbae6c2980b0ac6763f8c133d3235edc586762d6",
        "riscv64gc-unknown-linux-gnu": "9793f014e0b4c9541c10949d2b1ede0845083cd0323efb5128bdbea931e81525",
        "x86_64-apple-darwin": "95e9b074a8ea1a872765de0666e380588e1cfea8fa4e9966edbd3b0ef4e04e94",
        "x86_64-pc-windows-msvc": "9c13ef1cd0186e964f3a641a3861fb04fa79882d6b80af0941574908885f3cf3",
        "x86_64-unknown-linux-gnu": "4520b5c0ba0ad3b23b5a043c373be4937c4f42f55af9e53adb0257febbb1a5d2",
    },
)

ci_llvm(
    name = "ci_llvm",
    incoming_transition = ":stage0_configuration",
    rust_dev = ":rust_dev",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "frob",
    main = "frob.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "exec",
    main = "exec.py",
    visibility = ["PUBLIC"],
)
