buildscript.run = false
rustc_flags = ["-Zcrate-attr=allow(unfulfilled_lint_expectations)"]
omit_deps = [
    "rustc_codegen_ssa",
    "rustc_driver_impl",
    "rustc_smir",
    "stable_mir",
]

['cfg(target_os = "linux")']
linker_flags = ["-Wl,-rpath,$ORIGIN/../lib"]

['cfg(target_os = "macos")']
linker_flags = ["-Wl,-rpath,@loader_path/../lib"]
